app/playlists/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length

class NewPlaylistForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(max = 100)])
    submit = SubmitField("Create")

class AddSongToPlaylistForm(FlaskForm):
    title = StringField('Title', validators=[Length(max = 100)])
    artist = StringField('Artist', validators=[Length(max = 100)])
    submit = SubmitField("Add selected songs")

class OpenSharedPlaylistForm(FlaskForm):
    id = StringField('Id', validators=[DataRequired(), Length(max = 50)])
    submit = SubmitField("Search")

app/playlists/__init__.py
from flask import Blueprint

bp = Blueprint('playlists', __name__)

from app.playlists import routes

app/playlists/routes.py
from datetime import datetime
from app import db
from app.models import Playlist, Song
from app.playlists import bp
from app.playlists.forms import AddSongToPlaylistForm, NewPlaylistForm, OpenSharedPlaylistForm

from flask import render_template, flash, redirect, url_for, request, session, send_file
from flask_login import current_user, login_required

import os
import uuid

@bp.route("/playlists", methods = ["GET", "POST"])
@login_required
def playlists():
    from app.songs.routes import delete_user_temp_files
    delete_user_temp_files()

    create_form = NewPlaylistForm()

    if create_form.validate_on_submit():
        playlist = Playlist(name = create_form.name.data)

        db.session.add(playlist)
        current_user.playlists.append(playlist)
        db.session.commit()

        flash(f'Playlist "{playlist.name}" successfully created.')

    playlists = current_user.playlists.all()
    lengths = {p.name : len(p.songs) for p in playlists}

    # Calculate preview string
    max_length = 40
    playlist_preview = {}

    for p in playlists:
        j = 0
        if len(p.songs) == 0: 
            preview = "0"
        else:
            song_str = ""
            char_count = 0
            for i in range(len(p.songs)):
                song = p.songs[i]           
                song_str += song.title
                char_count += len(song.title)

                j += 1

                if char_count < max_length and i < len(p.songs) - 1:
                    song_str += ", "

                if char_count >= max_length and j != len(p.songs):
                    song_str += f", and {len(p.songs) - j} more"
                    break

            preview = f"{len(p.songs)} ({song_str})"
        playlist_preview[p.id] = preview

    # Show the default page
    return render_template(
        'playlists/playlists.html', 
        user = current_user, title = "Manage your playlists", 
        subtitle = "Songbook", 
        view = "playlists",
        playlists = playlists,
        lengths = lengths,
        playlist_preview = playlist_preview,
        create_form = create_form)


@bp.route('/edit', methods = ["GET", "POST"])
@login_required
def edit():
    args = list(request.form.items())
    print(args)

    if len(args) == 1: # if we come from the playlists page
        playlist_db_id = args[0][0]
        session["current_playlist_db_id"] = playlist_db_id
    else: # we get the form parameters
        playlist_db_id = session["current_playlist_db_id"]

    playlist = Playlist.query.get(playlist_db_id)
    if playlist == None:
        flash("Invalid operation.")
        return redirect(url_for("playlists.playlists"))
    
    songs = playlist.songs
    collection = current_user.songs.all()
    collection_by_id = {f'{x.id}' : x.to_dict() for x in collection}

    form = AddSongToPlaylistForm()
    
    submit_pressed = len(list(filter(lambda y : y[0] == "submit", args))) == 1 # make sure to not update when select or deselect is pressed
    
    if form.validate_on_submit() and submit_pressed: # We click "Add selected songs"
        # Add songs and show default page
        checked_song_ids = list(map(lambda x : int(x[0]), filter(lambda y : y[1] == "on", args)))
        
        for song_id in checked_song_ids:
            song_to_add = Song.query.get(song_id)

            if song_to_add not in playlist.songs:
                playlist.songs.append(song_to_add)
        db.session.commit()

        songs = playlist.songs

    songs_not_in_playlist = list(filter(lambda x : x not in songs, collection))

    # Show the default page
    return render_template(
        'playlists/edit.html', 
        user = current_user, title = 'Edit playlist', 
        subtitle = playlist.name, 
        view = "playlists",
        playlist = playlist,
        songs = songs,
        form = form,
        collection = collection,
        collection_by_id = collection_by_id,
    )


@bp.route('/delete', methods = ["POST"])
@login_required
def delete():
    args = list(request.form.items())
    
    playlist_db_id = args[0][0]

    playlist = Playlist.query.get(playlist_db_id)
    db.session.delete(playlist)
    db.session.commit()

    flash(f'Successfully removed the playlist "{playlist.name}".')

    return redirect(url_for("playlists.playlists"))


@bp.route('/remove', methods = ["POST"])
@login_required
def remove():
    playlist_db_id = session["current_playlist_db_id"]
    playlist = Playlist.query.get(playlist_db_id)

    args = list(request.form.items())
    id_to_remove = args[0][0]
    song_to_remove = Song.query.get(id_to_remove)
    playlist.songs.remove(song_to_remove)
    
    db.session.commit()
    
    return redirect(url_for("playlists.edit"))


@bp.route('/publish', methods = ["POST"])
@login_required
def publish():
    args = list(request.form.items())    
    playlist_db_id = args[0][0]   
    playlist = Playlist.query.get(playlist_db_id)

    if playlist.share:
        playlist.share_link = None
        playlist.share = False
    else:
        playlist.share_link = str(uuid.uuid4().hex)
        playlist.share = True

    db.session.commit()
    
    return redirect(url_for("playlists.playlists"))


@bp.route('/download', methods = ["POST"])
@login_required
def download():
    from app.songs.routes import delete_user_temp_files
    delete_user_temp_files()

    args = list(request.form.items())
    playlist_db_id = args[0][0]

    playlist = Playlist.query.get(playlist_db_id)

    pdf_path = build_songbook(playlist)
    path = os.path.join(*pdf_path.split("/")[1:])
    return send_file(path, as_attachment=True)


@bp.route('/shared/<link>', methods = ["GET", "POST"])
def shared(link):   
    playlist = Playlist.query.where(Playlist.share_link == link).first()   

    if playlist == None or not playlist.share:
        form = OpenSharedPlaylistForm()
        flash("This link does not belong to a public playlist.")
        return redirect(url_for(
            "playlists.shared_without_args", form = form))

    session["view_playlist"] = playlist.id

    return redirect(url_for("playlists.view_playlist"), code=307)


@bp.route('/open', methods = ["GET", "POST"])
def shared_without_args():
    form = OpenSharedPlaylistForm()

    if form.validate_on_submit():
        link = form.id.data.replace(" ", "")
        return shared(link)

    return render_template(
        "playlists/enter_link.html",
        form = form)


@bp.route('/view_playlist', methods = ["GET", "POST"])
def view_playlist():
    playlist = Playlist.query.get(int(session["view_playlist"]))
    if playlist == None:
        form = OpenSharedPlaylistForm()
        flash("Invalid operation")
        return redirect(url_for(
            "playlists.shared_without_args", form = form))

    author = playlist.user
    
    args = list(request.form.items())
    if len(args) > 0:
        command = args[0][0]

        if command == "AddSelectedToCollection":
            checked_song_ids = list(map(lambda x : int(x[0]), filter(lambda y : y[1] == "on", args)))
            
            if len(checked_song_ids) > 0:
                added_songs, already_known_songs = add_list_of_songs_to_collection(checked_song_ids)
                flash(f"{len(added_songs)} new songs were added to your collection, {'1 was' if len(already_known_songs) == 1 else str(len(already_known_songs)) + ' were' } already present.")
            else:
                flash("Please select songs to add.")

        elif command == "Songbook":
            pdf_path = build_songbook(playlist)
            path = os.path.join(*pdf_path.split("/")[1:])
            return send_file(path, as_attachment=True)

    return render_template(
        "playlists/shared_playlist.html",
        playlist = playlist,
        author = author,
        title = "Shared playlist",
        subtitle = f'"{playlist.name}" by {author.username}',
        songs = playlist.songs)


def add_list_of_songs_to_collection(song_ids):
    already_known_songs = []
    added_songs = []

    for song_id in song_ids:
        song_to_add = Song.query.get(song_id)

        already_known = False
        for s in current_user.songs:
            if s.equal(song_to_add):
                already_known_songs.append(song_to_add)
                already_known = True
                break
        if not already_known:
            copy = Song.copy(song_to_add)
            copy.added = datetime.now()
            copy.last_changed = datetime.now()
            
            current_user.songs.append(copy)            
            db.session.add(copy)
            added_songs.add(copy)
            
    db.session.commit()
    return added_songs, already_known_songs


def build_songbook(playlist):
    from app.songs.routes import get_user_path
    path = get_user_path("")

    if not os.path.exists("app/static"):
        os.mkdir("app/static")
    if not os.path.exists("app/static/tmp"):
        os.mkdir("app/static/tmp")
    if not os.path.exists(path):
        os.mkdir(path)

    from app.music.new_builder import create_songbook as build_songbook_pdf
    return build_songbook_pdf(playlist, current_user, path)

app/templates/playlists/enter_link.html
{% extends "base_centered.html" %}

{% block content %}

<div class="column is-4 is-offset-4">
    <h3 class="title">Shared playlist</h3>
    <div class="box">
        <div class="block">           
            {% with messages = get_flashed_messages() %}
                {% if messages %}  
                    {% for message in messages %}
                        <div class="notification is-danger">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %} 
            
            <form action="" method="POST">
                <p><b>Enter an id:</b></p>
                <br>
                {{ form.hidden_tag() }}
                <p>{{ form.id(class = "input") }}</p>
                <br>
                <p>{{ form.submit(class = "button") }}</p>
            </form>
        </div>        
    </div>
</div>


{% endblock %}

app/templates/playlists/playlists.html
{% extends "base.html" %}

{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <section class="section">
                {% for message in messages %}
                    <div class="notification is-danger">
                        {{ message }}
                    </div>
                {% endfor %}
            </section>
        {% endif %}
    {% endwith %}

    <section class="section">
        {% if playlists != [] %}
            <nav class="level">
                <div class="level-item has-text-centered">
                    <table class="table is-hoverable has-text-left">
                        <thead>
                            <tr>                        
                                <th>Name</th>
                                <th>Songs</th>
                                <th>Share link</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for playlist in playlists %}
                            <tr>
                                <td>{{ playlist.name }}</td>
                                <td>{{ playlist_preview[playlist.id] }}</td>
                                <td>
                                    {% if playlist.share %}
                                        <div class="field has-addons"> 
                                            <button class="button" name="{{playlist.id}}" onclick="copy_to_clipboard('{{ playlist.share_link }}')">
                                                <span class="icon is-small">
                                                    <i class="fas fa-copy"></i>
                                                </span>
                                            </button>

                                            <script>
                                                function copy_to_clipboard(l) {
                                                    var url = '{{ url_for("playlists.shared",  _external=True, link = "") }}' + l                                                    
                                                    navigator.clipboard.writeText(url);
                                                }
                                            </script>
                                            &nbsp
                                            {{ playlist.share_link }}
                                        </div>
                                    {% else %}
                                        private
                                    {% endif %}
                                </td>
                                
                                <td>
                                    <div class="field has-addons">
                                        <form name="form" action="publish" method="POST">
                                            {% if playlist.share %}
                                                <button class="button is-info" name="{{playlist.id}}">
                                                    <span class="icon is-small">
                                                        <i class="fas fa-bullhorn"></i>
                                                    </span>
                                                </button>
                                            {% else %}
                                                <button class="button is-success" name="{{playlist.id}}">
                                                    <span class="icon is-small">
                                                        <i class="fas fa-bullhorn"></i>
                                                    </span>
                                                </button>
                                            {% endif %}
                                        </form>

                                        &nbsp
                                        <form name="form" action="download" method="POST">
                                            <button class="button" name="{{playlist.id}}">
                                                <span class="icon is-small">
                                                    <i class="fas fa-book"></i>
                                                </span>
                                            </button>
                                        </form>  
                                        &nbsp
                                        <form name="form" action="edit" method="POST">
                                            <button class="button" name="{{playlist.id}}">
                                                <span class="icon is-small">
                                                    <i class="fas fa-edit"></i>
                                                </span>
                                            </button>
                                        </form>
                                        &nbsp
                                        <form name="form" action="delete" method="POST">
                                            <button class="button is-danger" name="{{playlist.id}}">
                                                <span class="icon is-small">
                                                    <i class="fas fa-trash"></i>
                                                </span>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                
            </nav>
        {% else %}
            <p class="subtitle">
                You haven't created any playlists.
            </p>
        {% endif %}
    </section>

    <div id="modal-new-playlist" class="modal">
        <div class="modal-background"></div>
      
        <div class="modal-content">
            <div class="box">
                <p class="subtitle">Create a new playlist</p>
                <form action="" method="POST">
                    {{ create_form.hidden_tag() }}
                    <p>{{ create_form.name(class = "input", placeholder = "Enter a name") }}</p>
                    <br>
                    <p>{{ create_form.submit(class = "button") }}</p>
                </form>
            </div>
        </div>      
    </div>
    <script>
        var forms = document.getElementsByName('form');

        // for (var j = 0; j < forms.length; j++) {
        //     var form = forms[j];
        //     form.addEventListener("submit", (e) => {
        //         disable_all_buttons();
        //         enable_loading_circle(e.submitter);
        //     });
        // }
       
        enable_all_buttons();

        function disable_all_buttons() {
            var buttons = document.getElementsByTagName('button');
            
            for (var i = 0; i < buttons.length; i++) {
                var b = buttons[i];                
                b.setAttribute('disabled', '');
            }
        }

        function enable_loading_circle(s) {
            s.classList.add("is-loading");
            s.classList.add("is-info");
        }

        function disable_loading_circle(s) {
            s.classList.remove("is-loading");            
            s.classList.remove("is-info");
        }

        function enable_all_buttons() {
            var buttons = document.getElementsByTagName('button');

            for (var i = 0; i < buttons.length; i++) {
                var b = buttons[i];
                b.classList.remove('disabled');
            }
        }
    </script>
{% endblock %}

app/templates/playlists/shared_playlist.html
{% extends "base.html" %}

{% block content %}

<section class="section">
    {% with messages = get_flashed_messages() %}
        {% if messages %}  
            {% for message in messages %}
                <div class="notification is-danger">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}          
    <form name="form" action="view_playlist" method="POST">
        <section class="section">
            <nav class="level">
                <div class="level-item has-text-centered">
                    <!-- <button class="button" onclick="select_all(); return false;">Select all</button>
                    &nbsp
                    <button class="button" onclick="deselect_all(); return false;">Deselect all</button>                
                    &nbsp
                    <p id="selected_count"></p>
                    &nbsp
                    &nbsp
                    &nbsp
                    <button class="button" name="AddSelectedToCollection">Add selected to your own collection</button>
                    &nbsp -->
                    <button class="button" name="Songbook">Songbook</button>
                </div>
            </nav>
            {% if songs != [] %}
            <table class="table is-fullwidth has-text-left is-hoverable">
                <thead>
                    <tr>
                        <th>Select</th>
                        <th>Cover</th>
                        <th>Title</th>
                        <th>Artist</th>
                        <th>Release</th>
                        <th>Year</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for song in songs %}
                    <tr>
                        <td>
                            <input type="checkbox" onclick="update_selected_count();" name="{{song.id}}">
                        </td>
                        <td>
                            <img width="64" height="64" id="{{song.release_id}}" />
                        </td>
                        <td>{{ song.title }}</td>
                        <td>{{ song.artist }}</td>
                        <td>{{ song.release }}</td>
                        <td>{{ song.year }}</td>
                        <td>
                            <div class="field has-addons">
                                <form action="../songs/collection/download" method="POST">
                                    <button class="button" name="{{song.id}}">
                                        <span class="icon is-small">
                                            <i class="fas fa-download"></i>
                                        </span>
                                    </button>
                                </form> 
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
        
                    <script>
                        var imgs = document.getElementsByTagName("img");
                        for (var i = 0; i < imgs.length; i++) {
                            img = imgs[i];
                            id = img.id;
                            fetch('http://coverartarchive.org/release/' + id)
                                .then(response => response.json())
                                .then(data => {
                                    for (var i = 0; i < data["images"].length; i++) {
                                        image = data["images"][i]
                                        if (image['types'].includes("Front")) {
                                            url = image['thumbnails']['small']
                                            if (url == null)
                                                url = image['thumbnails']['250']
                                            if (url == null)
                                                url = image['thumbnails']['500']
                                            if (url == null)
                                                url = image['image']

                                            id = url.split("/")[4]
                                            document.getElementById(id).src = url;
                                            break;
                                        }
                                    }
                                })
                                .catch(console.error);
                        }                              
                    </script>
                </tbody>
            </table>
            {% else %}
            <p class="subtitle">
                There are no songs in your playlist.
            </p>
            {% endif %}
        </section>
    </form>
</section>

<script>    
    function get_checkboxes() {
        var checkboxes = [];

        var inputs = document.getElementsByTagName("input");
        for (var i = 0; i < inputs.length; i++) {
            if (inputs[i].type == "checkbox") {
                checkboxes.push(inputs[i]);
            }
        }
        return checkboxes;
    }

    function update_selected_count() {
        var checkboxes = get_checkboxes();
        var selected = 0;

        for (var i = 0; i < checkboxes.length; ++i) {
            if (checkboxes[i].checked)
                selected++;
        }

        var selected_count = document.getElementById("selected_count");
        selected_count.innerText = selected + " selected";
    }

    function deselect_all() {
        var table = document.getElementsByTagName("table")[0];
        var rows = table.rows;
        var checkboxes = get_checkboxes();

        for (var i = 1; i < rows.length; ++i) {
            checkboxes[i - 1].checked = false;
        }
        update_selected_count();
    }

    function select_all() { 
        var table = document.getElementsByTagName("table")[0];
        var rows = table.rows;

        var checkboxes = get_checkboxes();

        for (var i = 1; i < rows.length; ++i) {               
            checkboxes[i - 1].checked = true;
        }
        update_selected_count();
    }

    // First time when loading the page
    update_selected_count();
</script>

{% endblock %}